### ISSUE TITLE
Luck of DB Schema

### ISSUE THREAD

**Issue by foxiness** [AeroCross/Snap#2]
As the current migration is either to append or drop a column to the original DB schema. Therefore, hope it include within it. either the SQL DUMP or the Complete Migration to build the DB as it on the development env on Local server.

**Comment by AeroCross** [comment]
Hey! This is something I actually wanted to do months and months ago and I forgot. I'll do this tomorrow hopefully.

**Comment by foxiness** [comment]
Thanks Mario for your response,

I'm so excited to get my hand on it.

**Comment by AeroCross** [comment]
All set.

Sorry that it's not localised though. It was just my undergrad thesis and I worked on it during weekend nights when I wasn't outside (which in hindsight, was more than I expected). Feel free to fork and PR!

Hope it's useful for ya :)
